language: python

python:
  - 3.4
  - 3.5
  - 3.6
  
before_install:
- pip install poetry nose

# Install renv
install:
- poetry install -v

# Command to run tests
# nosetests is being used as a default
script: nosetests tests/ --verbosity=3
